config/routes.rb
ClojuredocsPg::Application.routes.draw do
  devise_for :users, :path => "", :path_names => { :sign_in => 'login', :sign_out => 'logout' }, :controllers => { :sessions => "sessions" }

  resources :users
  resources :remarks

  match '/profile/:login' => 'users#profile', as: "user_profile"
  match '/search_autocomplete' => 'main#search_autocomplete'
  match '/search' => 'main#search'
  match '/search/:lib' => 'main#search'
  match '/ac_search' => 'main#lib_search'
  match '/ac_search/:lib' => 'main#lib_search'
  resources :examples
  resources :comments
  match '/quickref/:lib' => 'main#quick_ref_shortdesc'
  match '/quickref/shortdesc/:lib' => 'main#quick_ref_shortdesc'
  match '/quickref/varsonly/:lib' => 'main#quick_ref_vars_only'
  match '/feed/recent_updates' => 'feed#recent_updates'
  match '/see_also/lookup' => 'see_also#lookup'
  match '/see_also/delete' => 'see_also#delete'
  match '/see_also/vote' => 'see_also#vote'
  match '/see_also/add' => 'see_also#add'
  match '/v/:id' => 'main#function_short_link'
  match '/libs' => 'main#libs'
  match '/management/search/:lib' => 'management#search'
  match '/management/:lib/function' => 'management#function'
  match '/management/:lib' => 'management#index'
  match '/:lib/:version' => 'main#lib', :constraints => { :version => /\d+\.[^\/]*/ }
  match '/:lib/:version/builtin/(:type_class)$(:function)' => 'main#function', constraints: { version: /\d+\.[^\/]*/ }
  match '/:lib/:version/builtin/:type_class' => 'main#type_class', constraints: { :version => /\d+\.[^\/]*/}
  match '/:lib/:version/*ns/:type_class' => 'main#type_class', constraints: { :version => /\d+\.[^\/]*/, ns: /\w+(\/\w+)*?/, type_class: /[A-Z]+\w+/ }
  match '/:lib/:version/*ns/(:type_class)$(:function)' => 'main#function', constraints: { version: /\d+\.[^\/]*/, ns: /\w+(\/\w+)*?/, type_class: /[A-Z]+\w+/ }
  match '/:lib/:version/(*ns)$(:function)' => 'main#function', :constraints => { :version => /\d+\.[^\/]*/ }
  match '/:lib/:version/*ns' => 'main#ns', :constraints => { :version => /\d+\.[^\/]*/ }
  match '/:lib' => 'main#lib'
  match '/:lib/builtin/(:type_class)$(:function)' => 'main#function', constraints: { ns: /\w+(\/\w+)*?/ }
  match '/:lib/builtin/:type_class' => 'main#type_class', constraints: { ns: /\w+(\/\w+)*?/ }
  match '/:lib/*ns/:type_class' => 'main#type_class', constraints: { ns: /\w+(\/\w+)*?/, type_class: /[A-Z]+\w+/ }
  match '/:lib/*ns/(:type_class)$(:function)' => 'main#function', constraints: { ns: /\w+(\/\w+)*?/, type_class: /[A-Z]+\w+/ }
  match '/:lib/(*ns)$(:function)' => 'main#function', constraints: { ns: /\w+(\/\w+)*?/ }
  match '/:lib/*ns' => 'main#ns'
  root :to => "main#index"
end

app/models/example.rb
class Example < ActiveRecord::Base
  acts_as_versioned

  Example.versioned_class.class_eval do
    belongs_to :user
    belongs_to :examplable, polymorphic: true
  end

  belongs_to :examplable, polymorphic: true
  belongs_to :user
  
  def belongs_to?(user)
    return user_id == user.id
  end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_filter :authenticate_user!
  def new
  end

  def create
    #var_id = params[:var_id]
    #body = params[:example][:body] rescue nil
    #
    #@function = Function.find_by_id var_id
    #if not @function
    #  render json_fail "Couldn't find the var you'd like to add an example to."
    #  return
    #end

    #if not current_user
    #  render json_fail "You must be logged in to create an example."
    #  return
    #end
    @example = current_user.examples.new(params[:example])
    if (not @example.body) or @example.body == ""
      render json_fail "There was a problem saving your example, is it blank?"
    end
    
    if not @example.save
      render :json => {:success => false, :message => "Invalid example.", :errors => @example.errors}
    end
   
    render :json => {:success => true, 
                     :message => "Example added.", 
                     :example => {:body => @example.body,
                                  :function_id => @example.examplable_id,
                                  :id => @example.id,
                                  :user_id => @example.user_id},
                     :content => render_to_string(:partial => "example", :object => @example)}

  end
  
  def update
    
    example_id = params[:example_id]
    body = params[:example][:body] rescue nil
    
    if not current_user
      render json_fail "You must be logged in to update an example."
      return
    end
    
    @example = Example.find_by_id(example_id)
    if not @example
      render json_fail "There was a problem finding the example you were trying to update."
      return
    end
    
    if not body or body == ""
      render json_fail "There was a problem updating your example, is it blank?"
      return
    end
    
    # if not @example.user == current_user
    #       render json_fail "Sorry, you don't own the example you were trying up update."
    #       return
    # end
    
    @example.body = body
    @example.user = current_user
    
    if not @example.save
      render json_fail "There was a problem saving the example you updated."
      return
    end
    
    render :json => {:success => true,
                     :message => "Example updated.",
                     :example => {:body => @example.body,
                                  :function_id => @example.function_id,
                                  :id => @example.id,
                                  :user_id => @example.user_id},
                     :content => render_to_string(:partial => "example", :locals => {:e => @example})}
  end

  def delete

    id = params[:id]

    if not id
      render json_fail "Couldn't find the var you'd like to add an example to."
      return
    end

    if not current_user
      render json_fail "You must be logged in to delete an example."
      return
    end

    @example = Example.find_by_id_and_user_id(params[:id], current_user.id)
    if not @example
      render json_fail "Sorry, that example dosen't exist anymore, or you don't own it."
      return
    end

    @example.delete
    render :json => {:success => true, :message => "Example deleted."}
  end

  def show
    @example = Example.find(params[:id])
    if not @example
      flash[:message] = "Couldn't find the example you're looking for."
      redirect_back_or_default "/"
    end
  end
end

app/views/examples/_edit_example_form.html.erb
<div class="edit_example">
<%= form_for Example.new do |f| %>
Example Content <span class="instructions">(code only, do not wrap in &lt;pre&gt; tags. See <a href="/examples_style_guide">style guide</a> for more information.)</span>
<div class="examples_license">
	Examples submitted to Godock will be licensed under the <a href="http://creativecommons.org/publicdomain/zero/1.0/">Creative Commons CC 0</a>.
</div>
<%= image_tag "ajax-loader.gif", :class => "ajax_loader", :width => 20, :height => 20 %>
<%= f.text_area :body, :class=> 'textarea' %>
<div style="text-align: right">
	<a class="cancel" href="" style="float: left">Cancel</a>
	<!-- <input class="preview_example" type="button" value="Preview" /> -->
	<%= f.submit 'Update Example'%>
	<div class="clear"></div>
</div>
<input type="hidden" name="update_example" value="true" />
<input type="hidden" name="example_id" value="-1" />
<fieldset class="live_preview">
	<legend>Live Preview</legend>
	<div class="preview">
	</div>
</fieldset>
<% end %>

app/views/examples/_example.html.erb
<li>
<div class="example" id="example_<%= example.id %>">
  <% if (defined? hide_controls) && hide_controls #FIXME %>
  <div class="controls">
          <a class="permalink" name="example_<%= example.id %>" href="#example_<%= example.id %>">link</a>
          |
          <%= link_to 'changes', example, :class => 'view_changes', target: "_blank" %>
          <% if current_user %>
                  |
            <a href="#" class="edit" id="edit_<%= example.id %>">
                  edit
            </a> 
                  
                  <% if example.user == current_user %>
                  |
                  <%= link_to 'delete', example, method: :delete, class: "delete" %>
                  <% end %>
          <% end %>
  </div>
  <% end %>
  <div class="clear"></div>
  <div class="content">
    <pre class="brush: go; ruler: true">
<%= example.body %>
    </pre>
  </div>
  <div class="hidden plain_content"><%= example.body.gsub("<", "&lt;").gsub(">", "&gt;") %></div>
  <div class="clear"></div>
</div>
</li>

app/views/examples/show.html.erb
<script type="text/javascript" charset="utf-8">
  SyntaxHighlighter.all()
</script>
<div class="container_16">
  <div class="grid_16">
    <h1>Changes for <span class="ns"><%= @example.examplable.ns.name %>/</span><%= @example.examplable.name %></h1>

    <% @example.versions.reverse_each do |v| %>
      <div class="version">
              <div class="info">
                      <img src="<%= grav_url_for(v.user.email, 25) %>" /> 
                      <%= link_to v.user.login, user_profile_path(v.user) %>
                      <%= time_ago_or_time_stamp((v.updated_at || v.created_at)) %>
              </div>
              <ul>
                <%= render :partial => "examples/example", :locals => {:example => v, :hide_controls => true}%>
              </ul>
      </div>
    <% end %>
  </div>
</div>